export const profile = {
  name: "Renan W. M. da Cruz",
  role: "Engenheiro de Projetos & Excelência Operacional",
  location: "Catanduva – SP",
  phone: "(17) 99657-8098",
  email: "renancruz456@gmail.com",
  linkedin: "https://www.linkedin.com/in/renanwmcruz",
  available: "Disponível para mudança e viagens",
  summary: "Profissional com mais de 8 anos de atuação em empresas de médio e grande porte, orientado para o negócio. Formado em Engenharia Mecânica, com MBAs em Gestão de Projetos e Data Science & Analytics. Especialista em Lean Six Sigma, PMO e gestão estratégica de investimentos — transformando dados em decisões e processos em resultados.",
};

export const results = [
  { value: "R$ 5,3M", label: "Portfólio de savings gerenciados/ano" },
  { value: "R$ 740k", label: "Saving em projetos de embalagem" },
  { value: "9 Squads", label: "Liderança OKR" },
  { value: "R$ 400k", label: "Saving anual em redução de custos" },
  { value: "R$ 1,4M", label: "Budget gerenciado em layout" },
  { value: "3 ISOs", label: "Auditor interno certificado" },
];

export const experiences = [
  {
    title: "Coordenador de Produção",
    company: "DLA Pharmaceutical – Septodont Group",
    period: "Set/2025 – atual",
    current: true,
    bullets: [
      "Liderança e coordenação das operações produtivas em todos os turnos, garantindo metas de volume, qualidade, prazo e segurança",
      "Monitoramento contínuo de indicadores de performance (OEE) com análise de desvios e ações corretivas",
      "Interface com compras e demais departamentos para resolução de problemas técnicos",
      "Suporte técnico à implementação de novos processos e atividades de rotina",
      "Atuação como backup do Gerente de Produção",
      "Comitê de Cost Reduction – gestão de portfólio do site",
    ],
  },
  {
    title: "Especialista em Excelência Operacional",
    company: "DLA Pharmaceutical – Septodont Group",
    period: "Dez/2024 – Ago/2025",
    current: false,
    bullets: [
      "Foco em redução de desperdícios e implantação de cultura Lean",
      "Implantação de Sistema de Gestão de Performance (OEE)",
      "Treinamento e multiplicação do conhecimento em LEAN",
      "Projeto de melhoria no processo de embalagem – Saving R$ 260.000/ano",
      "Projeto de posicionadores de carpules – Saving estimado R$ 480.000/ano",
      "Comitê de Cost Reduction – gestão de portfólio do site",
    ],
  },
  {
    title: "Coordenador de Engenharia de Processos e PMO",
    company: "Animativa",
    period: "Mai/2022 – Nov/2024",
    current: false,
    bullets: [
      "Participação na definição de diretrizes alinhadas ao planejamento estratégico",
      "Gestão de investimentos estratégicos com elaboração de dashboard para o Conselho",
      "Gestão de portfólio de projetos de melhoria contínua – R$ 5.300.000/ano",
      "Desenvolvimento e gestão de projetos de melhoria contínua",
      "Líder OKR com 9 squads",
      "Implantação da área de SAC",
      "Auditor Interno das ISO 9001, 14001 e 45001",
    ],
  },
  {
    title: "Analista de Projetos e Processos PL",
    company: "Franklin Electric",
    period: "Mar/2021 – Abr/2022",
    current: false,
    bullets: [
      "Elaboração e treinamento em instruções de trabalho padronizadas",
      "Projetos de melhoria contínua em Montagem, Usinagem e Estamparia",
      "Participação no desenvolvimento de novos produtos com times do Brasil, Itália, México e EUA",
      "Mudança de layout de R$ 1,4 MM sem interrupções na produção",
      "Membro indicado da CIPA",
    ],
  },
];

export const projects = [
  {
    id: 1,
    title: "Implantação OEE – Sistema de Gestão de Performance",
    company: "DLA Pharmaceutical – Septodont Group",
    year: "2024–2025",
    category: "Excelência Operacional",
    tags: ["OEE", "Lean", "Power BI", "Produção"],
    description: "Implantação completa do sistema de OEE (Overall Equipment Effectiveness) na planta farmacêutica, criando dashboards em tempo real para monitoramento de performance produtiva e identificação de perdas.",
    challenge: "A planta não possuía indicadores estruturados de eficiência produtiva, tornando difícil identificar gargalos e perdas no processo. As decisões eram tomadas de forma reativa, sem dados consolidados.",
    solution: "Desenvolvimento de metodologia de coleta de dados, treinamento das equipes de produção e criação de painéis Power BI integrados ao chão de fábrica. Implantação de reuniões de gestão à vista com indicadores em tempo real.",
    result: "Aumento significativo da visibilidade sobre perdas produtivas, habilitando decisões proativas e sustentando os projetos de saving subsequentes. Base de dados para todos os projetos de melhoria do site.",
    impact: "Alto",
    icon: "⚙️",
  },
  {
    id: 2,
    title: "Projeto de Melhoria no Processo de Embalagem",
    company: "DLA Pharmaceutical – Septodont Group",
    year: "2025",
    category: "Lean Six Sigma",
    tags: ["Six Sigma", "Embalagem", "Saving", "DMAIC"],
    description: "Projeto de melhoria contínua aplicando metodologia DMAIC para redução de desperdícios e aumento de produtividade no processo de embalagem de produtos farmacêuticos.",
    challenge: "Processo de embalagem com alto índice de retrabalho, setup demorado e desperdício de materiais, gerando custos elevados e redução de capacidade produtiva.",
    solution: "Mapeamento detalhado do fluxo de valor (VSM), análise de causa-raiz com Ishikawa e 5 Por quês, padronização de setup, implementação de troca rápida (SMED) e controle estatístico do processo.",
    result: "Saving de R$ 260.000/ano com redução de retrabalho e otimização do setup. Padrões documentados e equipe treinada para sustentação dos resultados.",
    impact: "Alto",
    icon: "📦",
  },
  {
    id: 3,
    title: "Projeto Posicionadores de Carpules",
    company: "DLA Pharmaceutical – Septodont Group",
    year: "2025",
    category: "Engenharia de Produto",
    tags: ["Projeto", "Saving", "Manufatura", "R&D"],
    description: "Desenvolvimento de solução de engenharia para posicionadores de carpules (frascos de anestésicos), redesenhando o processo produtivo e reduzindo custos com insumos e retrabalho.",
    challenge: "Alto custo de produção dos posicionadores de carpules com desperdício de materiais e baixa padronização, impactando a rentabilidade do produto.",
    solution: "Engenharia de valor aplicada ao componente, redesenho do processo produtivo, seleção de materiais alternativos e validação técnica conforme normas do setor farmacêutico.",
    result: "Saving estimado de R$ 480.000/ano com aprovação técnica e início de implementação em escala.",
    impact: "Alto",
    icon: "🔬",
  },
  {
    id: 4,
    title: "Gestão de Portfólio de Savings – R$ 5,3M/ano",
    company: "Animativa",
    year: "2022–2024",
    category: "PMO & Gestão Estratégica",
    tags: ["PMO", "Portfólio", "OKR", "Estratégia"],
    description: "Estruturação e gestão de portfólio de projetos de melhoria contínua com impacto financeiro anual de R$ 5,3 milhões, incluindo apresentação para o Conselho e alinhamento estratégico.",
    challenge: "Ausência de estrutura formal de PMO para gestão de iniciativas de melhoria. Projetos eram executados de forma isolada, sem priorização por impacto ou alinhamento estratégico.",
    solution: "Criação da metodologia de portfólio, sistema de priorização por impacto x esforço, dashboard executivo para o Conselho, gestão de OKRs com 9 squads e rituais de acompanhamento quinzenal.",
    result: "Portfólio de R$ 5,3M/ano em savings gerenciados com visibilidade total ao Conselho. Cultura de melhoria contínua implantada com times autônomos.",
    impact: "Muito Alto",
    icon: "📊",
  },
  {
    id: 5,
    title: "Implantação do Comitê de Gestão de Investimentos",
    company: "Animativa",
    year: "2022–2023",
    category: "Gestão Financeira",
    tags: ["Investimentos", "Governança", "Dashboard", "Estratégia"],
    description: "Criação e implantação de comitê formal de análise e aprovação de investimentos estratégicos, com metodologia de avaliação de ROI, payback e alinhamento ao planejamento estratégico.",
    challenge: "Decisões de investimento sem critérios formalizados, gerando aprovações sem análise de retorno e desalinhamento com prioridades estratégicas da empresa.",
    solution: "Desenvolvimento de metodologia de análise de investimentos, templates de business case, criação de dashboard de acompanhamento e estruturação dos ritos do comitê com presença do Conselho.",
    result: "Governança de investimentos implantada com R$ 400.000/ano em saving via priorização correta de projetos. Processo replicável e documentado.",
    impact: "Alto",
    icon: "💼",
  },
  {
    id: 6,
    title: "Mudança de Layout – Orçamento R$ 1,4MM",
    company: "Franklin Electric",
    year: "2021–2022",
    category: "Engenharia de Produção",
    tags: ["Layout", "Projeto", "Manufatura", "Lean"],
    description: "Planejamento, programação e execução de mudança completa de layout fabril para viabilizar novo portfólio de produtos, com orçamento de R$ 1,4 milhões e sem impacto na produção corrente.",
    challenge: "Necessidade de reorganização completa do layout produtivo para acomodar novo portfólio, com restrição de não interromper a linha de produção existente durante a transição.",
    solution: "Planejamento detalhado em fases com simulação de fluxo, cronograma de execução por turnos, gestão de fornecedores de instalação e acompanhamento diário de progresso com lean construction.",
    result: "Entrega dentro do orçamento (R$ 1,4MM) e cronograma, sem interrupções prejudiciais à produção. Novo layout habilitou expansão do portfólio de produtos da empresa.",
    impact: "Alto",
    icon: "🏭",
  },
];

export const skills = {
  "Metodologias": ["Lean Six Sigma Black Belt", "WCM", "Kaizen / VSM", "OKR", "PMO", "DMAIC", "SMED", "5S"],
  "Dados & BI": ["Power BI", "Python", "R", "Excel Avançado", "Data Science", "Big Data"],
  "Gestão": ["Gestão de Portfólio", "Planejamento Estratégico", "Gestão de Investimentos", "Coaching", "Liderança de Squads"],
  "Qualidade": ["ISO 9001", "ISO 14001", "ISO 45001", "Auditor Interno", "Controle Estatístico"],
};

export const education = [
  { degree: "MBA em Data Science e Analytics", institution: "ESALQ – USP", year: "2022" },
  { degree: "MBA em Gerenciamento de Projetos", institution: "UNIFAFIBE", year: "2020" },
  { degree: "Graduação em Engenharia Mecânica", institution: "UNIFEB", year: "2017" },
];

export const certifications = [
  { name: "Black Belt Lean Six Sigma", org: "FM2S", year: "2020" },
  { name: "Gerenciamento de Portfólio e PMO", org: "FGV", year: "2022" },
  { name: "Power BI para Data Science 2.0", org: "Data Science Academy", year: "2022" },
  { name: "Especialista Lean Manufacturing", org: "FM2S", year: "2019" },
  { name: "WCM – World Class Manufacturing", org: "FM2S", year: "2019" },
  { name: "Cronoanálise com BPM e Lean Thinking", org: "Udemy", year: "2019" },
  { name: "Big Data Real-time com Python e Spark", org: "", year: "" },
];
